---
title: ""
---

<font size="6"> Book</font>

<font size="3"> Cunha Silva, Patrick, Andrew Janusz, and Andrea Junqueira. "Intersectional Institutionalism: How District Magnitude Affects the Representation of Marginalized Groups." Under contract with *Cambridge University Press*. </font>

<button class="btn btn-primary btn-sm" data-toggle="collapse" data-target="#BlockName20" center> Abstract </button>  
<div id="BlockName20" class="collapse">  

There is a consensus that electoral institutions affect how well legislatures descriptively represent their citizens. Most research to date, however, assumes that institutions affect members of different groups in the same way. In this book project, we draw on intersectional theories, which recognize gender and racial identities as mutually constitutive and interconnected, and contend that institutions have disparate effects on individuals holding different combinations of gender and racial identities. Our argument focuses primarily on district magnitude, which, when increased, leads aspiring politicians, party leaders, and voters to act in very different ways. Using a massive dataset with information on three different Brazilian elections and more than 1.2 million candidates, we estimate the causal impact of district magnitude on the emergence and electoral success of candidates with different gender and racial identities, both independently as well as interactively. We show that district magnitude has a positive effect on the emergence of candidates from historically underrepresented groups, but the size of the effect varies across groups. Moreover, we show that more diverse candidate fields do not translate into more diverse legislatures. In Brazil, as district magnitude increases, elected legislatures become less representative of women (whites and Afro-Brazilians) because competition increases and their access to campaign resources declines. These results demonstrate that electoral institutions have disparate effects on individuals with different combinations of race-gender identities.

</div>

<br /> 

<font size="6"> Peer-Reviewed Articles</font>

<font size="3"> Junqueira, Andrea, Diana O'Brien, Matthew Hayes, Jongwoo Jeong, Brian Crisp, and Matthew Gable. Forthcoming. "Race, Gender, and Nascent Political Ambition." *British Journal of Political Science*. </font>

<button class="btn btn-primary btn-sm" data-toggle="collapse" data-target="#BlockName15" center> Abstract </button>  
<div id="BlockName15" class="collapse">  

How do race and gender together shape Americans' political ambition? Using original survey data with over-samples of Black and Hispanic respondents, we analyze citizens' nascent ambition for eight political offices across racial/ethnic groups and gender. We reveal that the primary gap in nascent political ambition is not between men and women but between white men and the majority of the polity. There is no consistent gender gap in ambition among Black or Hispanic respondents, nor between Black and Hispanic men and white women. The gap between white men and other respondents is most pronounced for local offices, which mark both the starting point and final stage of many political careers. Our findings further indicate that while white men are particularly responsive to encouragement from non-political sources, ambition gaps narrow among respondents encouraged by political actors. Together, these insights help explain the persistence of white men's overrepresentation in U.S. politics.

</div>

<br /> 

<font size="3"> Janusz, Andrew, Patrick Cunha Silva, and Andrea Junqueira. 2025. "Electoral Role Models: Political Empowerment and Candidate Emergence." *Political Behavior*, 47(2), 573-598. Available [here](https://link.springer.com/article/10.1007/s11109-024-09959-1).</font> 

<button class="btn btn-primary btn-sm" data-toggle="collapse" data-target="#BlockName7" center> Abstract </button>  
<div id="BlockName7" class="collapse">  

Does the election of politicians from historically marginalized groups spur others to enter politics? Some political scientists and policymakers posit that the election of women and people of color to prominent political offices can inspire others to run for office, yet prior research has yielded mixed results. We contribute to the literature on representation by exploring the impact of role models on candidate emergence at the local level, where aspiring politicians typically begin to climb the political ladder. Using data from Brazilian elections and a set of regression discontinuity designs, we find no evidence that the election of a woman or Afro-Brazilian mayor spurs women and Afro-Brazilians to run for city council positions. Our results, which are robust to several alternative specifications, suggest that even if the election of a woman or minority politician inspires others to enter politics, barriers may impede them from running for office.

</div>

<br />


<font size="3"> Junqueira, Andrea, Thiago Silva, and Guy Whitten. 2025. "Coalition as a Heuristic: Voters' Perceptions of Party Positions in Presidential Multiparty Democracies." *Journal of Elections, Public Opinion, and Parties*, 35(2), 288-307. Available [here](https://www.tandfonline.com/doi/full/10.1080/17457289.2024.2427022).</font>

<button class="btn btn-primary btn-sm" data-toggle="collapse" data-target="#BlockName14" center> Abstract </button>  
<div id="BlockName14" class="collapse">  

The ability of voters to accurately perceive the ideological positions of political parties
is foundational to the democratic process. Existing research has demonstrated
that in parliamentary democracies, voters rely on information about coalition status
to navigate the complexities of placing parties on an ideologically coherent scale. We
contribute to this literature by investigating the role of coalitions as a heuristic tool
in presidential democracies. We argue that the central role of the president in coalition
formation and operation, combined with the higher complexity of party systems,
makes coalition information in these democracies more accessible and understandable
primarily among sophisticated voters. Testing our hypotheses with data from three
presidential democracies, we find, as expected, that sophisticated voters are more likely
than less sophisticated voters to perceive parties in coalition with the president's party
as ideologically closer to the party of the president.

</div>

<br /> 


<font size="3"> Junqueira, Andrea, and Patrick Cunha Silva. 2024. "Strengthening the Party, Weakening the Women: Unforeseen Consequences of Strengthening Institutions." *The Journal of Politics*, 86(2), 734-748. Available [here](https://www.journals.uchicago.edu/doi/10.1086/726966).</font> 

<button class="btn btn-primary btn-sm" data-toggle="collapse" data-target="#BlockName2" center> Abstract </button>  
<div id="BlockName2" class="collapse">  

The party politics literature suggests that an institutionalized party system can be key for well-functioning democracies. Do the benefits of strong parties also extend to women's descriptive representation? We argue that increasing parties' strength can perpetuate and even intensify parties' pre-existing patterns of exclusion of particular groups, including women, when elites are gender-biased. While stronger parties are better able to carry out their organizational goals, we contend that increasing gender equity is often not part of such goals. To evaluate this argument, we combine an exogenous electoral reform that increased parties' ability to control their members in Brazil with a regression discontinuity design. We find that while the reform increased parties' ability to pursue their organizational goals, it increased the gap in votes between men and women. Further, we demonstrate that the behavior of men towards women co-partisans drives this pattern. These findings highlight the unintended consequences of institutional engineering.

</div>

<br /> 


<font size="3"> Eastman, Abbie, Andrea Junqueira, Ali Kagalwala, Andrew Philips, and Guy Whitten. 2024. "Volatile Pies: Modeling Compositional Volatility." *Social Science Quarterly*, 105(4), 965-979. Available [here](https://onlinelibrary.wiley.com/doi/full/10.1111/ssqu.13406).</font> 

<button class="btn btn-primary btn-sm" data-toggle="collapse" data-target="#BlockName6" center> Abstract </button>  
<div id="BlockName6" class="collapse">  

*Objective*: To demonstrate the utility of modeling compositional volatility in substantive domains beyond budgeting. *Methods*: We show how to model compositional volatility on its own or as a part of a system of equations in which the component parts of the compositional outcome variable are also modeled. *Results*: Using data on the volatility of support for German political parties, we demonstrate the usefulness of stand-alone models of compositional volatility. Using data on the volatility of income shares in the United States, we demonstrate the usefulness of modeling volatility together with compositional components. *Conclusion*: There is considerable potential for modeling compositional volatility.

</div>

<br /> 


<font size="3"> Junqueira, Andrea, Ali Kagalwala, and Christine Lipsmeyer. 2023. "What's Your Problem? How Issue Ownership and Partisan Discourse Influence Personal Concerns." *Social Science Quarterly*, 104(1), 25-37. Available [here](https://doi.org/10.1111/ssqu.13259).</font>

<button class="btn btn-primary btn-sm" data-toggle="collapse" data-target="#BlockName3" center> Abstract </button>  
<div id="BlockName3" class="collapse">  

*Objective*: Politics around the world has become more divisive. We ask if the influence of far-right parties extends to personal concerns and argue that a theory combining issue ownership with partisan discourse can explain personal policy salience. *Method*: Using aggregate Eurobarometer data, we create compositional models to estimate the effect of partisan discourse on pocketbook policy concerns. We focus on whether these elite messages influence concerns differently depending on the presence of a far-right party. *Results*: We find that more partisan discussion about law-and-order issues influences relative personal concerns on security and immigration issues across ideological groups when a far-right party is present. *Conclusions*: Our findings suggest that an "issue owning" party can alter how people interpret politics and view their own concerns. Far-right parties influence the perceptions of people across ideologies. Research showed that these parties can influence parties and voters; we show that they can shape personal perceptions.

</div>

<br /> 


<font size="3"> Junqueira, Andrea, Thiago Silva, and Guy Whitten. 2023. "What About Us? Political Competition, Economic Performance, Immigration, and Nativist Appeals." *Social Science Quarterly*, 104(1), 11-24. Available [here](https://doi.org/10.1111/ssqu.13240).</font>

<button class="btn btn-primary btn-sm" data-toggle="collapse" data-target="#BlockName4" center> Abstract </button>  
<div id="BlockName4" class="collapse">  

*Objective*: To develop and test theoretical expectations about when political parties will make more or fewer nativist appeals in their electoral campaigns. *Methods*: We use spatial autoregressive models to test our claims about the ways in which electoral competition drives nativist appeals. *Results*: We find strong support for our theoretical expectations on how spatial and temporal processes influence parties' nativist appeals. We also find strong support for our expectations on how the percentage of foreign-born population shapes nativist appeals by government
parties and how economic performance shapes nativist appeals by opposition parties. *Conclusion*: Spatial party competition conditions the relationship between economic performance, immigration, and parties' nativist appeals, revealing the strategic behavior of political parties in their choices of when to make nativist appeals more or less prominent in their electoral campaigns.

</div>

<br /> 


<font size="3"> Barberia, Lorena, Maria Leticia Claro Oliveira, Andrea Junqueira, Natalia Moreria, and Guy Whitten. 2021. "Should I Stay or Should I Go? Embracing Causal Heterogeneity in the Study of Pandemic Policy and Citizen Behavior." *Social Science Quarterly*, 102(5), 2055-2069. Available [here](https://onlinelibrary.wiley.com/doi/10.1111/ssqu.13037).</font> 

<button class="btn btn-primary btn-sm" data-toggle="collapse" data-target="#BlockName" center> Abstract </button>  
<div id="BlockName" class="collapse">  

*Objective*: To test for multicausality between government policy, health outcomes, economic performance, and citizen behavior during the COVID-19 global pandemic. *Methods*: We perform Granger-causality tests to explore the interrelationship between four endogenous variables, social distancing policy, home isolation, balance rate, and average weekly COVID-19 deaths, in the 26 states of Brazil. As exogenous variables, we included a linear time trend and a dummy for the week in which the World Health Organization (WHO) declared COVID-19 a global pandemic. *Results*:
Our analysis of Granger causal ordering between the four variables demonstrates that there is significant heterogeneity across the Brazilian federation. These findings can be interpreted as underscoring that there is no common model applicable to all states, and that the dynamics are context-dependent. *Conclusion*: Our suggested approach allows researchers to account for the complex interrelationship between government policy, citizen behavior, the economy, and COVID-related health outcomes.

</div>

<br /> 


<font size="6"> Under Review </font>

<font size="3"> Cheibub, Jose, Andrea Junqueira, and Thiago Moreira. "Preventing a War of All Against All: Geographic Sorting in OLPR Electoral Systems." *Under review*. </font>

<button class="btn btn-primary btn-sm" data-toggle="collapse" data-target="#BlockName10" center> Abstract </button>  
<div id="BlockName10" class="collapse">  

In open-list proportional representation (OLPR) systems, candidates must obtain personal votes to succeed. Conventional wisdom about these systems is that they induce intraparty competition and, ultimately, weak political parties. In this paper, we argue that, even under extreme institutional conditions, parties face incentives to limit competition among co-partisans. To evaluate this argument, we create the first measure of intraparty competition to incorporate the spatial distribution of all votes in the district. Using polling station-level data in Brazil, we show that about fifty percent of parties coordinate competition among co-partisans by limiting the number of strong candidates in the list or selecting candidates whose electoral bases do not overlap. We also show that electorally strong parties are more prone to coordination and that coordination leads to electoral success. Our findings challenge the perception of weak parties in OLPR systems, highlighting strategic coordination as a prevalent phenomenon even in permissive electoral environments.

</div>

<br /> 


<font size="3"> Eastman, Abbie, Andrea Junqueira, Ali Kagalwala, Andrew Philips, and Guy Whitten. "Endogenous Pie: Modeling Simultaneity in Dynamic Models of Compositional Outcomes." *Under Review*. </font>

<button class="btn btn-primary btn-sm" data-toggle="collapse" data-target="#BlockName12" center> Abstract </button>  
<div id="BlockName12" class="collapse">  

Recent advances in the analysis of compositional data have extended the applicability of compositional-outcome models from cross-sectional data to time series and time-series-cross-section data. These models can explicitly account for the temporal and spatial dynamics in one's theory. While these advances are many, and important, the models presented thus far assume that regressors are weakly exogenous. In this letter, we relax the assumption of weak-exogeneity by introducing a model that accounts for simultaneity between compositional outcomes and endogenous non-compositional
variables in time series data. Our approach involves creating what we call a compositional vector
autoregression framework. We demonstrate the utility of our modeling approach with an application that analyzes income inequality in the United States.

</div>

<br /> 


<font size="6"> Selected Work in Progress</font>

<font size="3"> Junqueira, Andrea. "Who Gets Seen? Incumbency Advantage and the Limits of Public Campaign Finance for Representation, " *In Progress*. </font>

<br /> 


<font size="3"> Junqueira, Andrea. "The Political Economy of the Heavy Hand: How Poverty Reduces Politicians' Incentives to Reform Security Policies." *In Progress*. </font>

<br /> 


<font size="3"> Junqueira, Andrea and Christine Lipsmeyer. "Legal Equality and Effective Inequality: Mapping Representation Across Neighborhoods in Brazil." *In progress*. </font>

<br /> 


<font size="3"> Cooperman, Alicia, Andrea Junqueira, Thiago Moreira, and Manuela Munoz. "Local Distributive Politics: Municipal Legislative Behavior and Neighborhood Service Provision in Brazil." *In progress*. </font>

<br /> 


<font size="3"> Cheibub, Jose, Andrea Junqueira, and Thiago Moreira. "Legal Equality and Effective Inequality: Mapping Representation Across Neighborhoods in Brazil." *In progress*. </font>

<br /> 








