---
title: ""
---

<font size="6"> **Teaching**</font>

<br /> 

<font size="4"> ***Instructor of Record*** </font>


<font size="2"> **Arkansas State University** </font>

<p>POSC 3203: Introduction to Comparative Politics<br>
Undergraduate level<br>
Fall 2024, Fall 2025<br>
<a href="./POSC3203(63455.202460)2024FallINTRODUCTIONTOCOMPARATIVEPOLITICS(POSC-3203-001)_AndreaJunqueiraMachado.pdf" target="_blank">Evaluations Fall 2024 (PDF)</a> <br>

<p>POSC 3003: Introduction to Political Analysis<br>
Undergraduate level<br>
Fall 2023, Spring 2024, Fall 2024, Spring 2025, Fall 2025<br>
<a href="./POSC3003(61350.202360)2023FallINTRODUCTIONTOPOLITICALANALYSIS(POSC-3003-001)_AndreaJunqueiraMachado.pdf" target="_blank">Evaluations Fall 2023 (PDF)</a> <br>
<a href="./POSC3003(11131.202410)2024SpringINTRODUCTIONTOPOLITICALANALYSIS(POSC-3003-002)_AndreaJunqueiraMachado.pdf" target="_blank">Evaluations Spring 2024 (PDF)</a> <br>
<a href="./POSC3003(61262.202460)2024FallINTRODUCTIONTOPOLITICALANALYSIS(POSC-3003-001)_AndreaJunqueiraMachado.pdf" target="_blank">Evaluations Fall 2024 (PDF)</a> <br>
<a href="./POSC3003(11021.202510)2025SpringINTRODUCTIONTOPOLITICALANALYSIS(POSC-3003-002)_AndreaJunqueiraMachado.pdf" target="_blank">Evaluations Spring 2025 (PDF)</a> <br>

<p>POSC 4003/680V: Special Topics: Latin America<br>
Undergraduate and Master's level<br>
Spring 2024, Spring 2025<br>
<a href="./POSC4003(14225.202410)2024SpringSPLATINAMERICANPOLITICS(POSC-4003-003)_AndreaJunqueiraMachado.pdf" target="_blank">Evaluations Spring 2024 (PDF)</a> <br>
<a href="./POSC4003(13012.202510)2025SpringSPLATINAMERICANPOLITICS(POSC-4003-003)_AndreaJunqueiraMachado.pdf" target="_blank">Evaluations Spring 2025 (PDF)</a> <br>

<p>POSC 4143: Public Opinion and Public Policy<br>
Undergraduate level<br>
Fall 2023<br>
<a href="./POSC4143(64689.202360)2023FallPUBLICOPINIONANDPUBLICPOLICY(POSC-4143-001)_AndreaJunqueiraMachado.pdf" target="_blank">Evaluations Fall 2023 (PDF)</a> <br>

<font size="2"> **Texas A&M University** </font>

<p>POLS 323: Political Systems of Latin America<br>
Undergraduate level<br>
Fall 2021 and Spring 2022<br>
<a href="./survey_results_aggregate_20220103_1632.pdf" target="_blank">Evaluations Fall 2021 (PDF)</a> <br>
<a href="./survey_results_aggregate_20220823_1014.pdf" target="_blank">Evaluations Spring 2022 (PDF)</a> </p>

<br /> 

<font size="4"> ***Teaching Assistant (Graduate Level)*** </font>

<p>POLS 621: Theory and Method in Comparative Politics<br>
Texas A&M University<br>
Professor: Florian Hollenbach<br>
Fall 2020</p>

<p>POLS 602: Quantitative Political Analysis<br>
Texas A&M University<br>
Professor: Paul Kellstedt<br>
Fall 2019</p>

<p>FLP 0406: Quantitative Research in Political Science<br>
University of São Paulo<br>
Professor: Glauco Peres<br>
Spring 2016</p>

<br /> 

<font size="4"> ***Teaching Assistant (Undergraduate Level)*** </font>

<p>POLS 209: Introduction to Political Science Research<br>
Texas A&M University<br>
Professor: Dominique Lewis<br>
Spring 2019</p>

<br /> 

<font size="4"> ***Teaching Assistant (International Political Science Association IPSA Summer School)*** </font>

<p>Modern Regression Analysis<br>
IPSA Summer School - Singapore<br>
Professors: Guy Whitten and Katsunori Seki<br>
July 2020</p>

<p>Causal Inference and Field Experiments<br>
IPSA Summer School - São Paulo<br>
Professor: Florian Foos<br>
January 2020</p>

